-- ======================================================================
-- IOCL Digital Pump Manager - Remote Demo Seed SQL
-- Generated automatically by scripts/exportDemoSeedSql.ts
-- ======================================================================

PRAGMA foreign_keys = OFF;

-- Table: audit_logs (1 rows)
INSERT OR IGNORE INTO "audit_logs" ("id", "user_id", "action", "entity_type", "entity_id", "old_value_json", "new_value_json", "ip_address", "user_agent", "created_at") VALUES ('audit-init-001', 'user-admin', 'SYSTEM_SEED', 'SYSTEM', 'SYSTEM', NULL, '{"message":"IOCL Digital Pump Manager database seeded successfully with Phase 1, 2A & 2B infrastructure"}', '127.0.0.1', 'D1 Seeder Engine', '2026-10-06T04:37:34.077Z');

-- Table: dispensers (2 rows)
INSERT OR IGNORE INTO "dispensers" ("id", "outlet_id", "dispenser_number", "name", "manufacturer", "model", "serial_number", "status", "commissioned_at", "created_at", "updated_at", "created_by") VALUES ('disp-ro1-1', 'ro-1001', 1, 'Multi-Product Dispenser 01 (MPD-1)', 'Wayne Dresser', 'Helix 5000', 'WD-2023-01991', 'ACTIVE', '2023-01-20T00:00:00Z', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "dispensers" ("id", "outlet_id", "dispenser_number", "name", "manufacturer", "model", "serial_number", "status", "commissioned_at", "created_at", "updated_at", "created_by") VALUES ('disp-ro1-2', 'ro-1001', 2, 'Multi-Product Dispenser 02 (MPD-2)', 'Gilbarco Veeder-Root', 'Horizon', 'GVR-2023-08812', 'ACTIVE', '2023-01-20T00:00:00Z', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');

-- Table: divisions (2 rows)
INSERT OR IGNORE INTO "divisions" ("id", "state_id", "code", "name", "status", "created_at", "updated_at") VALUES ('div-kol', 'state-wb', 'KOL-DO', 'Kolkata Divisional Office', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "divisions" ("id", "state_id", "code", "name", "status", "created_at", "updated_at") VALUES ('div-ldh', 'state-pb', 'LDH-DO', 'Ludhiana Divisional Office', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');

-- Table: nozzles (4 rows)
INSERT OR IGNORE INTO "nozzles" ("id", "outlet_id", "dispenser_id", "nozzle_number", "product_id", "tank_id", "status", "created_at", "updated_at", "created_by") VALUES ('nozz-ro1-1-1', 'ro-1001', 'disp-ro1-1', 1, 'prod-ms', 'tank-ro1-1', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "nozzles" ("id", "outlet_id", "dispenser_id", "nozzle_number", "product_id", "tank_id", "status", "created_at", "updated_at", "created_by") VALUES ('nozz-ro1-1-2', 'ro-1001', 'disp-ro1-1', 2, 'prod-hsd', 'tank-ro1-2', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "nozzles" ("id", "outlet_id", "dispenser_id", "nozzle_number", "product_id", "tank_id", "status", "created_at", "updated_at", "created_by") VALUES ('nozz-ro1-2-1', 'ro-1001', 'disp-ro1-2', 1, 'prod-ms', 'tank-ro1-1', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "nozzles" ("id", "outlet_id", "dispenser_id", "nozzle_number", "product_id", "tank_id", "status", "created_at", "updated_at", "created_by") VALUES ('nozz-ro1-2-2', 'ro-1001', 'disp-ro1-2', 2, 'prod-hsd', 'tank-ro1-2', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');

-- Table: outlet_product_prices (15 rows)
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-1', 'ro-1001', 'prod-ms', 9520, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-2', 'ro-1001', 'prod-hsd', 9530, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-3', 'ro-1001', 'prod-xp95', 9540, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-4', 'ro-1001', 'prod-xtragreen', 9550, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-5', 'ro-1001', 'prod-cng', 9560, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-6', 'ro-1002', 'prod-ms', 9570, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-7', 'ro-1002', 'prod-hsd', 9580, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-8', 'ro-1002', 'prod-xp95', 9590, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-9', 'ro-1002', 'prod-xtragreen', 9600, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-10', 'ro-1002', 'prod-cng', 9610, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-11', 'ro-1003', 'prod-ms', 9620, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-12', 'ro-1003', 'prod-hsd', 9630, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-13', 'ro-1003', 'prod-xp95', 9640, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-14', 'ro-1003', 'prod-xtragreen', 9650, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_product_prices" ("id", "outlet_id", "product_id", "price_paise_per_unit", "effective_from", "effective_to", "status", "created_at", "created_by") VALUES ('opp-seed-15', 'ro-1003', 'prod-cng', 9660, '1900-01-01', NULL, 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');

-- Table: outlet_products (3 rows)
INSERT OR IGNORE INTO "outlet_products" ("id", "outlet_id", "product_id", "status", "created_at", "created_by") VALUES ('op-ro1-ms', 'ro-1001', 'prod-ms', 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_products" ("id", "outlet_id", "product_id", "status", "created_at", "created_by") VALUES ('op-ro1-hsd', 'ro-1001', 'prod-hsd', 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "outlet_products" ("id", "outlet_id", "product_id", "status", "created_at", "created_by") VALUES ('op-ro1-xp95', 'ro-1001', 'prod-xp95', 'ACTIVE', '2026-10-06T04:37:34.077Z', 'user-admin');

-- Table: outlet_user_assignments (2 rows)
INSERT OR IGNORE INTO "outlet_user_assignments" ("id", "outlet_id", "user_id", "assignment_type", "effective_from", "effective_to", "is_active", "created_at", "created_by") VALUES ('oua-1', 'ro-1001', 'user-dealer', 'DEALER', '2026-10-06T04:37:34.077Z', NULL, 1, '2026-10-06T04:37:34.077Z', 'SYSTEM');
INSERT OR IGNORE INTO "outlet_user_assignments" ("id", "outlet_id", "user_id", "assignment_type", "effective_from", "effective_to", "is_active", "created_at", "created_by") VALUES ('oua-2', 'ro-1001', 'user-csp', 'CSP', '2026-10-06T04:37:34.077Z', NULL, 1, '2026-10-06T04:37:34.077Z', 'SYSTEM');

-- Table: permissions (82 rows)
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-prod-r', 'products.read', 'Read Products', 'View master fuel products catalog');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-prod-mg', 'products.manage_global', 'Manage Global Products', 'Manage global products catalog');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-oprod-r', 'outlet_products.read', 'Read Outlet Products', 'View outlet product assignments');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-oprod-w', 'outlet_products.write', 'Write Outlet Products', 'Assign products to outlet');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-tank-r', 'tanks.read', 'Read Tanks', 'View underground storage tank master');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-tank-w', 'tanks.write', 'Write Tanks', 'Manage underground storage tanks');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-disp-r', 'dispensers.read', 'Read Dispensers', 'View dispenser units master');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-disp-w', 'dispensers.write', 'Write Dispensers', 'Manage dispenser units');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-nozz-r', 'nozzles.read', 'Read Nozzles', 'View dispensing nozzles master');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-nozz-w', 'nozzles.write', 'Write Nozzles', 'Manage dispensing nozzles');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-stm-r', 'shift_templates.read', 'Read Shift Templates', 'View shift templates');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-stm-w', 'shift_templates.write', 'Write Shift Templates', 'Configure shift templates');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-shf-r', 'shifts.read', 'Read Shifts', 'View operational shifts');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-shf-o', 'shifts.open', 'Open Shifts', 'Open operational shifts');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-shf-c', 'shifts.close', 'Close Shifts', 'Close operational shifts');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-rdg-r', 'meter_readings.read', 'Read Meter Readings', 'View nozzle meter readings');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-rdg-w', 'meter_readings.write', 'Write Meter Readings', 'Record meter readings and unavailability');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-tcal-r', 'tank_calibration.read', 'Read Tank Calibration', 'View tank calibration charts and points');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-tcal-w', 'tank_calibration.write', 'Write Tank Calibration', 'Manage tank calibration charts and import data');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-tstk-r', 'tank_stock.read', 'Read Tank Stock', 'View tank physical dips and stock readings');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-tstk-w', 'tank_stock.write', 'Write Tank Stock', 'Record opening, closing, and ad-hoc tank dips');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-rcpt-r', 'fuel_receipts.read', 'Read Fuel Receipts', 'View tanker fuel receipts and delivery records');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-rcpt-w', 'fuel_receipts.write', 'Write Fuel Receipts', 'Record tanker delivery, decantation, and line measurements');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-qual-r', 'quality.read', 'Read Quality Parameters', 'View density and temperature quality records');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-qual-w', 'quality.write', 'Write Quality Parameters', 'Record fuel receipt density and temperature observations');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-qtol-m', 'quality_tolerance.manage', 'Manage Quality Tolerances', 'Configure scope-based density and quality tolerance rules');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-srec-r', 'stock_reconciliation.read', 'Read Stock Reconciliation', 'View shift and product level stock reconciliation summaries');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-price-r', 'product_prices.read', 'Read product prices', 'Can view outlet product prices');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-price-w', 'product_prices.write', 'Write product prices', 'Can manage outlet product prices');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-cparty-r', 'credit_parties.read', 'Read credit parties', 'Can view outlet credit parties');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-cparty-w', 'credit_parties.write', 'Write credit parties', 'Can manage outlet credit parties');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-coll-r', 'collections.read', 'Read collections', 'Can view shift collections');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-coll-w', 'collections.write', 'Write collections', 'Can manage shift collections');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-chand-r', 'cash_handover.read', 'Read cash handover', 'Can view cash handover logs');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-chand-w', 'cash_handover.write', 'Write cash handover', 'Can manage cash handover logs');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-chand-a', 'cash_handover.acknowledge', 'Acknowledge cash handover', 'Can acknowledge cash handover logs');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-bdep-r', 'bank_deposits.read', 'Read bank deposits', 'Can view bank deposit logs');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-bdep-w', 'bank_deposits.write', 'Write bank deposits', 'Can manage bank deposit logs');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-bdep-v', 'bank_deposits.verify', 'Verify bank deposits', 'Can verify bank deposit logs');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-frec-r', 'financial_reconciliation.read', 'Read financial reconciliation', 'Can view financial reconciliation reports');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-cng-read', 'cng_operations.read', 'Read CNG Operations', 'Allows viewing CNG operational logs and pressure readings');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-cng-write', 'cng_operations.write', 'Write CNG Operations', 'Allows creating and managing CNG operational logs and pressure readings');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-lube-read', 'lube_operations.read', 'Read Lube Operations', 'Allows viewing lube inventory, stock ledger, prices, and shift sales');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-lube-inv-write', 'lube_inventory.write', 'Write Lube Inventory', 'Allows managing lube SKU catalog, stock receipts, and inventory adjustments');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-lube-sales-write', 'lube_sales.write', 'Write Lube Shift Sales', 'Allows recording and updating shift lube sales');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-lube-prices-write', 'lube_prices.write', 'Write Lube Prices', 'Allows creating and managing lube selling price masters');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-eq-r', 'equipment.read', 'Read Equipment', 'View equipment assets and breakdown tickets');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-eq-as-w', 'equipment_assets.write', 'Write Equipment Assets', 'Manage equipment assets');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-eq-t-c', 'equipment_tickets.create', 'Create Equipment Tickets', 'Create new breakdown tickets');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-eq-t-m', 'equipment_tickets.manage', 'Manage Equipment Tickets', 'Assign and resolve breakdown tickets');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-eq-t-s', 'equipment_tickets.signoff', 'Signoff Equipment Tickets', 'Sign off and close breakdown tickets');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-util-r', 'utilities.read', 'Read Utilities', 'View electricity accounts, bills, sub-meters, and readings');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-util-acc-w', 'utilities.accounts.write', 'Write Utility Accounts', 'Manage electricity accounts');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-util-bill-w', 'utilities.bills.write', 'Write Utility Bills', 'Create and update electricity bills');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-util-pay-w', 'utilities.payments.write', 'Write Utility Payments', 'Record payments for utility bills');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-util-sub-w', 'utilities.sub_meters.write', 'Write Utility Sub-Meters', 'Manage electricity sub-meters');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-util-read-w', 'utilities.sub_meter_readings.write', 'Write Utility Sub-Meter Readings', 'Record sub-meter electricity readings');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-mtax-r', 'municipal_taxes.read', 'Read Municipal Taxes', 'View property taxes, trade license fees, signage charges, and statutory payment status');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-mtax-w', 'municipal_taxes.write', 'Write Municipal Taxes', 'Create and update municipal tax assessments and statutory due records');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-mtax-pay-w', 'municipal_taxes.payments.write', 'Record Municipal Tax Payments', 'Record statutory due payments with mandatory receipt attachment');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-nfr-r', 'nfr.read', 'Read NFR Operations', 'View NFR spaces, vendors, leases, rent dues, and payment records');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-nfr-master-w', 'nfr.master.write', 'Write NFR Master Data', 'Create and update NFR spaces and vendor masters');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-nfr-lease-w', 'nfr.leases.write', 'Write NFR Leases', 'Create, update, and terminate NFR lease agreements');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-nfr-due-w', 'nfr.rent_dues.write', 'Generate NFR Rent Dues', 'Generate monthly authoritative rent dues for NFR leases');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-nfr-pay-w', 'nfr.rent_payments.write', 'Record NFR Rent Payments', 'Record rent collections and payment receipts for NFR rent dues');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-hr-r', 'hr.read', 'Read HR & Workforce', 'View designations, staff master, manpower sanctions, summary, and shift roster');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-hr-staff-w', 'hr.staff.write', 'Write Staff & Designations', 'Create and update HR designations and staff profiles');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-hr-manpower-w', 'hr.manpower.write', 'Write Manpower Sanctions', 'Create and update sanctioned manpower counts');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-hr-roster-w', 'hr.roster.write', 'Write Shift Roster', 'Create and update shift roster assignments');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-u-r', 'users.read', 'Read Users', 'View user profiles within scope');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-u-c', 'users.create', 'Create Users', 'Provision new system users');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-u-u', 'users.update', 'Update Users', 'Modify user details and status');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-h-r', 'hierarchy.read', 'Read Hierarchy', 'View state, division, sales area structures');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-h-w', 'hierarchy.write', 'Write Hierarchy', 'Manage state, division, sales area structures');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-o-r', 'outlets.read', 'Read Outlets', 'View retail outlet records and master data');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-o-c', 'outlets.create', 'Create Outlets', 'Register new retail outlets');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-o-u', 'outlets.update', 'Update Outlets', 'Modify outlet master details');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-s-r', 'scopes.read', 'Read Scopes', 'View user scope assignments');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-s-a', 'scopes.assign', 'Assign Scopes', 'Modify user organizational scopes');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-d-r', 'documents.read', 'Read Documents', 'View outlet documents');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-d-w', 'documents.write', 'Write Documents', 'Upload and manage documents');
INSERT OR IGNORE INTO "permissions" ("id", "code", "name", "description") VALUES ('perm-a-r', 'audit.read', 'Read Audit Logs', 'View system audit trail');

-- Table: products (5 rows)
INSERT OR IGNORE INTO "products" ("id", "code", "name", "category", "unit", "status", "created_at", "updated_at") VALUES ('prod-ms', 'MS', 'Motor Spirit (Petrol)', 'MS', 'LITRE', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "products" ("id", "code", "name", "category", "unit", "status", "created_at", "updated_at") VALUES ('prod-hsd', 'HSD', 'High Speed Diesel', 'HSD', 'LITRE', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "products" ("id", "code", "name", "category", "unit", "status", "created_at", "updated_at") VALUES ('prod-xp95', 'XP95', 'XP95 Premium Petrol', 'XP95', 'LITRE', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "products" ("id", "code", "name", "category", "unit", "status", "created_at", "updated_at") VALUES ('prod-xtragreen', 'XTRAGREEN', 'XTRAGREEN Diesel', 'XTRAGREEN', 'LITRE', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "products" ("id", "code", "name", "category", "unit", "status", "created_at", "updated_at") VALUES ('prod-cng', 'CNG', 'Compressed Natural Gas', 'CNG', 'KG', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');

-- Table: quality_tolerance_settings (2 rows)
INSERT OR IGNORE INTO "quality_tolerance_settings" ("id", "scope_type", "scope_entity_id", "product_id", "density_tolerance_milliunits", "status", "effective_from", "effective_to", "created_at", "created_by") VALUES ('qts-global-default', 'GLOBAL', NULL, NULL, 3000, 'ACTIVE', '2024-01-01', '2027-12-31', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "quality_tolerance_settings" ("id", "scope_type", "scope_entity_id", "product_id", "density_tolerance_milliunits", "status", "effective_from", "effective_to", "created_at", "created_by") VALUES ('qts-ms-global', 'GLOBAL', NULL, 'prod-ms', 2500, 'ACTIVE', '2024-01-01', '2027-12-31', '2026-10-06T04:37:34.077Z', 'user-admin');

-- Table: retail_outlets (3 rows)
INSERT OR IGNORE INTO "retail_outlets" ("id", "ro_code", "name", "outlet_type", "state_id", "division_id", "sales_area_id", "address", "city", "district", "pincode", "latitude", "longitude", "status", "created_at", "updated_at") VALUES ('ro-1001', 'RO-110023', 'Park Street IOCL Service Station', 'COCO', 'state-wb', 'div-kol', 'sa-cen', '45 Park Street, Chowringhee', 'Kolkata', 'Kolkata', '700016', 22.5532, 88.3526, 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "retail_outlets" ("id", "ro_code", "name", "outlet_type", "state_id", "division_id", "sales_area_id", "address", "city", "district", "pincode", "latitude", "longitude", "status", "created_at", "updated_at") VALUES ('ro-1002', 'RO-110024', 'Salt Lake City Sector V Retail Outlet', 'CODO', 'state-wb', 'div-kol', 'sa-nor', 'Block GP, Sector V, Salt Lake', 'Kolkata', 'North 24 Parganas', '700091', 22.5726, 88.4331, 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "retail_outlets" ("id", "ro_code", "name", "outlet_type", "state_id", "division_id", "sales_area_id", "address", "city", "district", "pincode", "latitude", "longitude", "status", "created_at", "updated_at") VALUES ('ro-1003', 'RO-110025', 'GT Road Ludhiana Fuel Outlet', 'A_SITE', 'state-pb', 'div-ldh', 'sa-ldh-cen', '100 GT Road, Miller Ganj', 'Ludhiana', 'Ludhiana', '141003', 30.901, 75.8573, 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');

-- Table: role_permissions (303 rows)
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-eq-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-eq-as-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-eq-t-c');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-eq-t-m');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-eq-t-s');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-eq-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-eq-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-eq-t-m');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-eq-t-s');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-eq-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-eq-as-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-eq-t-m');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-eq-t-s');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-eq-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-eq-as-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-eq-t-m');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-eq-t-s');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-eq-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-eq-as-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-eq-t-c');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-eq-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-eq-as-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-eq-t-c');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-util-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-util-acc-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-util-bill-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-util-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-util-sub-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-util-read-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-util-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-util-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-util-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-util-acc-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-util-bill-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-util-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-util-sub-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-util-read-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-util-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-util-acc-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-util-bill-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-util-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-util-sub-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-util-read-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-util-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-util-bill-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-util-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-util-read-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-util-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-util-bill-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-util-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-util-read-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-mtax-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-mtax-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-mtax-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-mtax-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-mtax-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-mtax-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-mtax-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-mtax-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-mtax-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-mtax-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-mtax-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-mtax-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-mtax-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-mtax-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-mtax-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-nfr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-nfr-master-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-nfr-lease-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-nfr-due-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-nfr-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-nfr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-nfr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-nfr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-nfr-master-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-nfr-lease-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-nfr-due-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-nfr-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-nfr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-nfr-master-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-nfr-lease-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-nfr-due-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-nfr-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-nfr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-nfr-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-nfr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-nfr-pay-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-hr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-hr-staff-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-hr-manpower-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-hr-roster-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-hr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-hr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-hr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-hr-staff-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-hr-manpower-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-hr-roster-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-hr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-hr-staff-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-hr-manpower-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-hr-roster-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-hr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-hr-staff-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-hr-roster-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-hr-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-hr-staff-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-hr-roster-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-u-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-u-c');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-u-u');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-h-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-h-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-o-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-o-c');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-o-u');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-s-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-s-a');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-d-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-d-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-a-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-prod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-prod-mg');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-oprod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-oprod-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-tank-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-tank-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-disp-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-disp-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-nozz-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-nozz-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-stm-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-stm-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-shf-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-shf-o');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-shf-c');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-rdg-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-rdg-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-tcal-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-tcal-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-tstk-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-tstk-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-rcpt-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-rcpt-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-qual-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-qual-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-qtol-m');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-srec-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-cng-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-cng-write');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-lube-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-lube-inv-write');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-lube-sales-write');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-admin', 'perm-lube-prices-write');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-u-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-u-c');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-u-u');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-h-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-o-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-s-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-s-a');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-d-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-a-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-prod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-oprod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-tank-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-disp-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-nozz-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-stm-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-shf-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-rdg-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-tcal-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-tstk-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-rcpt-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-qual-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-qtol-m');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-srec-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-cng-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-so', 'perm-lube-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-u-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-u-c');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-u-u');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-h-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-o-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-o-u');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-s-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-d-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-d-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-a-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-prod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-oprod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-tank-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-disp-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-nozz-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-stm-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-shf-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-rdg-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-tcal-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-tstk-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-rcpt-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-qual-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-srec-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-cng-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-do', 'perm-lube-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-u-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-h-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-o-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-s-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-d-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-a-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-prod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-oprod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-tank-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-disp-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-nozz-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-stm-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-shf-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-rdg-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-tcal-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-tstk-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-rcpt-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-qual-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-srec-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-cng-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-bm', 'perm-lube-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-h-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-o-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-o-u');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-d-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-d-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-prod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-oprod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-tank-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-disp-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-nozz-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-stm-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-shf-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-rdg-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-tcal-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-tstk-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-rcpt-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-qual-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-srec-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-cng-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-fo', 'perm-lube-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-o-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-d-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-d-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-prod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-oprod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-oprod-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-tank-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-tank-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-disp-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-disp-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-nozz-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-nozz-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-stm-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-stm-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-shf-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-shf-o');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-shf-c');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-rdg-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-rdg-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-tcal-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-tcal-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-tstk-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-tstk-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-rcpt-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-rcpt-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-qual-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-qual-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-srec-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-cng-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-cng-write');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-lube-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-lube-inv-write');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-dealer', 'perm-lube-sales-write');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-o-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-d-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-prod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-oprod-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-tank-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-disp-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-nozz-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-stm-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-shf-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-shf-o');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-shf-c');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-rdg-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-rdg-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-tcal-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-tstk-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-tstk-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-rcpt-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-rcpt-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-qual-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-qual-w');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-srec-r');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-cng-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-cng-write');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-lube-read');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-lube-inv-write');
INSERT OR IGNORE INTO "role_permissions" ("role_id", "permission_id") VALUES ('role-csp', 'perm-lube-sales-write');

-- Table: roles (7 rows)
INSERT OR IGNORE INTO "roles" ("id", "code", "name", "description") VALUES ('role-admin', 'ADMIN', 'System Administrator', 'Full access across all organizational units and capabilities');
INSERT OR IGNORE INTO "roles" ("id", "code", "name", "description") VALUES ('role-so', 'STATE_OFFICE', 'State Office Executive', 'State-level oversight, user scope management, and monitoring');
INSERT OR IGNORE INTO "roles" ("id", "code", "name", "description") VALUES ('role-do', 'DIVISIONAL_OFFICE', 'Divisional Office Manager', 'Divisional operations management and outlet supervision');
INSERT OR IGNORE INTO "roles" ("id", "code", "name", "description") VALUES ('role-bm', 'BUSINESS_MANAGER', 'Business Manager', 'Regional business analytics and field officer supervision');
INSERT OR IGNORE INTO "roles" ("id", "code", "name", "description") VALUES ('role-fo', 'FIELD_OFFICER', 'Field Officer', 'Field level inspection and retail outlet compliance manager');
INSERT OR IGNORE INTO "roles" ("id", "code", "name", "description") VALUES ('role-dealer', 'DEALER', 'Retail Outlet Dealer', 'Outlet franchisee / owner with access to assigned outlet operations');
INSERT OR IGNORE INTO "roles" ("id", "code", "name", "description") VALUES ('role-csp', 'CSP', 'Customer Service Provider', 'Outlet staff / attendant with operational data access');

-- Table: sales_areas (3 rows)
INSERT OR IGNORE INTO "sales_areas" ("id", "division_id", "code", "name", "status", "created_at", "updated_at") VALUES ('sa-cen', 'div-kol', 'KOL-CEN-SA', 'Kolkata Central Sales Area', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "sales_areas" ("id", "division_id", "code", "name", "status", "created_at", "updated_at") VALUES ('sa-nor', 'div-kol', 'KOL-NOR-SA', 'Kolkata North Sales Area', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "sales_areas" ("id", "division_id", "code", "name", "status", "created_at", "updated_at") VALUES ('sa-ldh-cen', 'div-ldh', 'LDH-CEN-SA', 'Ludhiana Central Sales Area', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');

-- Table: shift_templates (4 rows)
INSERT OR IGNORE INTO "shift_templates" ("id", "outlet_id", "code", "name", "start_time", "end_time", "sequence", "status", "created_at", "updated_at", "created_by") VALUES ('st-ro1-1', 'ro-1001', 'SHIFT_1', 'Shift 1 (Morning)', '06:00', '14:00', 1, 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "shift_templates" ("id", "outlet_id", "code", "name", "start_time", "end_time", "sequence", "status", "created_at", "updated_at", "created_by") VALUES ('st-ro1-2', 'ro-1001', 'SHIFT_2', 'Shift 2 (Evening)', '14:00', '22:00', 2, 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "shift_templates" ("id", "outlet_id", "code", "name", "start_time", "end_time", "sequence", "status", "created_at", "updated_at", "created_by") VALUES ('st-ro1-3', 'ro-1001', 'SHIFT_3', 'Shift 3 (Night Overnight)', '22:00', '06:00', 3, 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "shift_templates" ("id", "outlet_id", "code", "name", "start_time", "end_time", "sequence", "status", "created_at", "updated_at", "created_by") VALUES ('st-ro1-gen', 'ro-1001', 'GENERAL', 'General Shift', '09:00', '18:00', 4, 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');

-- Table: states (2 rows)
INSERT OR IGNORE INTO "states" ("id", "code", "name", "status", "created_at", "updated_at") VALUES ('state-wb', 'WBSO', 'West Bengal State Office', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "states" ("id", "code", "name", "status", "created_at", "updated_at") VALUES ('state-pb', 'PPSO', 'Punjab State Office', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');

-- Table: tank_calibration_points (24 rows)
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t1-000', 'tank-ro1-1', 0, 0, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t1-250', 'tank-ro1-1', 250000, 1200000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t1-500', 'tank-ro1-1', 500000, 3100000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t1-750', 'tank-ro1-1', 750000, 5600000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t1-1000', 'tank-ro1-1', 1000000, 8500000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t1-1250', 'tank-ro1-1', 1250000, 11500000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t1-1500', 'tank-ro1-1', 1500000, 14400000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t1-1750', 'tank-ro1-1', 1750000, 16900000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t1-2000', 'tank-ro1-1', 2000000, 18800000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t1-2250', 'tank-ro1-1', 2250000, 19700000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t1-2500', 'tank-ro1-1', 2500000, 20000000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t2-000', 'tank-ro1-2', 0, 0, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t2-500', 'tank-ro1-2', 500000, 3800000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t2-1000', 'tank-ro1-2', 1000000, 9500000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t2-1500', 'tank-ro1-2', 1500000, 15500000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t2-2000', 'tank-ro1-2', 2000000, 21200000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t2-2500', 'tank-ro1-2', 2500000, 24500000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t2-2800', 'tank-ro1-2', 2800000, 25000000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t3-000', 'tank-ro1-3', 0, 0, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t3-500', 'tank-ro1-3', 500000, 2500000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t3-1000', 'tank-ro1-3', 1000000, 6800000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t3-1500', 'tank-ro1-3', 1500000, 11200000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t3-2000', 'tank-ro1-3', 2000000, 14500000, '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tank_calibration_points" ("id", "tank_id", "dip_millimetres_milliunits", "volume_milliunits", "created_at", "created_by") VALUES ('tcp-t3-2200', 'tank-ro1-3', 2200000, 15000000, '2026-10-06T04:37:34.077Z', 'user-admin');

-- Table: tanks (3 rows)
INSERT OR IGNORE INTO "tanks" ("id", "outlet_id", "tank_number", "name", "product_id", "capacity_litres", "safe_fill_capacity_litres", "minimum_operating_level_litres", "status", "commissioned_at", "created_at", "updated_at", "created_by") VALUES ('tank-ro1-1', 'ro-1001', 1, 'Tank 1 - MS (20 KL)', 'prod-ms', 20000, 19000, 1000, 'ACTIVE', '2023-01-15T00:00:00Z', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tanks" ("id", "outlet_id", "tank_number", "name", "product_id", "capacity_litres", "safe_fill_capacity_litres", "minimum_operating_level_litres", "status", "commissioned_at", "created_at", "updated_at", "created_by") VALUES ('tank-ro1-2', 'ro-1001', 2, 'Tank 2 - HSD (25 KL)', 'prod-hsd', 25000, 23750, 1500, 'ACTIVE', '2023-01-15T00:00:00Z', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');
INSERT OR IGNORE INTO "tanks" ("id", "outlet_id", "tank_number", "name", "product_id", "capacity_litres", "safe_fill_capacity_litres", "minimum_operating_level_litres", "status", "commissioned_at", "created_at", "updated_at", "created_by") VALUES ('tank-ro1-3', 'ro-1001', 3, 'Tank 3 - XP95 (15 KL)', 'prod-xp95', 15000, 14250, 1000, 'ACTIVE', '2023-01-15T00:00:00Z', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z', 'user-admin');

-- Table: user_roles (7 rows)
INSERT OR IGNORE INTO "user_roles" ("user_id", "role_id") VALUES ('user-admin', 'role-admin');
INSERT OR IGNORE INTO "user_roles" ("user_id", "role_id") VALUES ('user-so', 'role-so');
INSERT OR IGNORE INTO "user_roles" ("user_id", "role_id") VALUES ('user-do', 'role-do');
INSERT OR IGNORE INTO "user_roles" ("user_id", "role_id") VALUES ('user-bm', 'role-bm');
INSERT OR IGNORE INTO "user_roles" ("user_id", "role_id") VALUES ('user-fo', 'role-fo');
INSERT OR IGNORE INTO "user_roles" ("user_id", "role_id") VALUES ('user-dealer', 'role-dealer');
INSERT OR IGNORE INTO "user_roles" ("user_id", "role_id") VALUES ('user-csp', 'role-csp');

-- Table: user_scope_assignments (7 rows)
INSERT OR IGNORE INTO "user_scope_assignments" ("id", "user_id", "scope_level", "state_id", "division_id", "sales_area_id", "outlet_id", "created_at", "created_by") VALUES ('scope-admin', 'user-admin', 'GLOBAL', NULL, NULL, NULL, NULL, '2026-10-06T04:37:34.077Z', 'SYSTEM');
INSERT OR IGNORE INTO "user_scope_assignments" ("id", "user_id", "scope_level", "state_id", "division_id", "sales_area_id", "outlet_id", "created_at", "created_by") VALUES ('scope-so', 'user-so', 'STATE', 'state-wb', NULL, NULL, NULL, '2026-10-06T04:37:34.077Z', 'SYSTEM');
INSERT OR IGNORE INTO "user_scope_assignments" ("id", "user_id", "scope_level", "state_id", "division_id", "sales_area_id", "outlet_id", "created_at", "created_by") VALUES ('scope-do', 'user-do', 'DIVISION', NULL, 'div-kol', NULL, NULL, '2026-10-06T04:37:34.077Z', 'SYSTEM');
INSERT OR IGNORE INTO "user_scope_assignments" ("id", "user_id", "scope_level", "state_id", "division_id", "sales_area_id", "outlet_id", "created_at", "created_by") VALUES ('scope-bm', 'user-bm', 'DIVISION', NULL, 'div-kol', NULL, NULL, '2026-10-06T04:37:34.077Z', 'SYSTEM');
INSERT OR IGNORE INTO "user_scope_assignments" ("id", "user_id", "scope_level", "state_id", "division_id", "sales_area_id", "outlet_id", "created_at", "created_by") VALUES ('scope-fo', 'user-fo', 'SALES_AREA', NULL, NULL, 'sa-cen', NULL, '2026-10-06T04:37:34.077Z', 'SYSTEM');
INSERT OR IGNORE INTO "user_scope_assignments" ("id", "user_id", "scope_level", "state_id", "division_id", "sales_area_id", "outlet_id", "created_at", "created_by") VALUES ('scope-dealer', 'user-dealer', 'OUTLET', NULL, NULL, NULL, 'ro-1001', '2026-10-06T04:37:34.077Z', 'SYSTEM');
INSERT OR IGNORE INTO "user_scope_assignments" ("id", "user_id", "scope_level", "state_id", "division_id", "sales_area_id", "outlet_id", "created_at", "created_by") VALUES ('scope-csp', 'user-csp', 'OUTLET', NULL, NULL, NULL, 'ro-1001', '2026-10-06T04:37:34.077Z', 'SYSTEM');

-- Table: users (7 rows)
INSERT OR IGNORE INTO "users" ("id", "emp_code", "name", "email", "phone", "password_hash", "status", "created_at", "updated_at") VALUES ('user-admin', 'IOCL-ADM-001', 'Rajesh Sharma', 'admin@iocl.in', '9830000001', '$2b$10$LRWtTGKyFutdAief2r69HuQ4qj8NiTVmGo60ncRYAdKKULU.3VvkC', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "users" ("id", "emp_code", "name", "email", "phone", "password_hash", "status", "created_at", "updated_at") VALUES ('user-so', 'IOCL-SO-001', 'Ananya Roy', 'wbso@iocl.in', '9830000002', '$2b$10$LRWtTGKyFutdAief2r69HuQ4qj8NiTVmGo60ncRYAdKKULU.3VvkC', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "users" ("id", "emp_code", "name", "email", "phone", "password_hash", "status", "created_at", "updated_at") VALUES ('user-do', 'IOCL-DO-001', 'Vikram Banerjee', 'kolkatado@iocl.in', '9830000003', '$2b$10$LRWtTGKyFutdAief2r69HuQ4qj8NiTVmGo60ncRYAdKKULU.3VvkC', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "users" ("id", "emp_code", "name", "email", "phone", "password_hash", "status", "created_at", "updated_at") VALUES ('user-bm', 'IOCL-BM-001', 'Ramesh Krishnan', 'bm.kolkata@iocl.in', '9830000007', '$2b$10$LRWtTGKyFutdAief2r69HuQ4qj8NiTVmGo60ncRYAdKKULU.3VvkC', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "users" ("id", "emp_code", "name", "email", "phone", "password_hash", "status", "created_at", "updated_at") VALUES ('user-fo', 'IOCL-FO-001', 'Subhashish Das', 'fo.central@iocl.in', '9830000004', '$2b$10$LRWtTGKyFutdAief2r69HuQ4qj8NiTVmGo60ncRYAdKKULU.3VvkC', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "users" ("id", "emp_code", "name", "email", "phone", "password_hash", "status", "created_at", "updated_at") VALUES ('user-dealer', 'IOCL-DLR-001', 'Pritam Mukherjee', 'dealer.parkstreet@iocl.in', '9830000005', '$2b$10$LRWtTGKyFutdAief2r69HuQ4qj8NiTVmGo60ncRYAdKKULU.3VvkC', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');
INSERT OR IGNORE INTO "users" ("id", "emp_code", "name", "email", "phone", "password_hash", "status", "created_at", "updated_at") VALUES ('user-csp', 'IOCL-CSP-001', 'Rahul Sen', 'csp.parkstreet@iocl.in', '9830000006', '$2b$10$LRWtTGKyFutdAief2r69HuQ4qj8NiTVmGo60ncRYAdKKULU.3VvkC', 'ACTIVE', '2026-10-06T04:37:34.077Z', '2026-10-06T04:37:34.077Z');

PRAGMA foreign_keys = ON;
